CheckingSystem/src/Entity/Subject.php
<?php

namespace App\Entity;

use App\Repository\SubjectRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SubjectRepository::class)]
class Subject
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $teacherName = null;

    #[ORM\Column]
    private ?\DateTime $start_at = null;

    #[ORM\Column]
    private ?\DateTime $end_at = null;

    #[ORM\Column(length: 255)]
    private ?string $subjectName = null;

    #[ORM\Column(type: "datetime_immutable", options: ["default" => "CURRENT_TIMESTAMP"])]
    private $created_at;

    #[ORM\ManyToOne(inversedBy: 'subject_id')]
    private ?Schedule $schedule = null;

    #[ORM\Column(length: 7)]
    private ?string $background_color = null;

    #[ORM\Column(nullable: true)]
    private ?bool $all_day = null;

    #[ORM\Column(length: 7, nullable: true)]
    private ?string $border_color = null;

    #[ORM\Column(length: 7)]
    private ?string $text_color = null;

    #[ORM\ManyToOne(inversedBy: 'subjects')]
    private ?Schedule $schedule_id = null;


    public function __construct()
    {
        $this->created_at = new \DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTeacherName(): ?string
    {
        return $this->teacherName;
    }

    public function setTeacherName(string $teacherName): self
    {
        $this->teacherName = $teacherName;

        return $this;
    }

    public function getStartAt(): ?\DateTime
    {
        return $this->start_at;
    }

    public function setStartAt(\DateTime $start_at): self
    {
        $this->start_at = $start_at;

        return $this;
    }

    public function getEndAt(): ?\DateTime
    {
        return $this->end_at;
    }

    public function setEndAt(\DateTime $end_at): self
    {
        $this->end_at = $end_at;

        return $this;
    }

    public function getSubjectName(): ?string
    {
        return $this->subjectName;
    }

    public function setSubjectName(string $subjectName): self
    {
        $this->subjectName = $subjectName;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getSchedule(): ?Schedule
    {
        return $this->schedule;
    }

    public function setSchedule(?Schedule $schedule): self
    {
        $this->schedule = $schedule;

        return $this;
    }

    public function getBackgroundColor(): ?string
    {
        return $this->background_color;
    }

    public function setBackgroundColor(string $background_color): self
    {
        $this->background_color = $background_color;

        return $this;
    }

    public function isAllDay(): ?bool
    {
        return $this->all_day;
    }

    public function setAllDay(?bool $all_day): self
    {
        $this->all_day = $all_day;

        return $this;
    }

    public function getBorderColor(): ?string
    {
        return $this->border_color;
    }

    public function setBorderColor(?string $border_color): self
    {
        $this->border_color = $border_color;

        return $this;
    }

    public function getTextColor(): ?string
    {
        return $this->text_color;
    }

    public function setTextColor(string $text_color): self
    {
        $this->text_color = $text_color;

        return $this;
    }

    public function getScheduleId(): ?Schedule
    {
        return $this->schedule_id;
    }

    public function setScheduleId(?Schedule $schedule_id): self
    {
        $this->schedule_id = $schedule_id;

        return $this;
    }
}

CheckingSystem/src/Controller/MainController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Student;
use Doctrine\Persistence\ManagerRegistry;

#[Route('/', name: 'app_')]
class MainController extends AbstractController
{
    public function __construct(ManagerRegistry $doctrine)
    {
        $this->doctrine = $doctrine;
    }

    #[Route('/', name: 'main')]
    public function index(): Response
    {
        if (!$this->getUser()) { // connection check
            return $this->redirectToRoute('app_login');
        }
        // return to another route
        return $this->redirectToRoute('app_home');
    }
}

CheckingSystem/templates/main/home.html.twig
{% extends "base.html.twig" %}

{% block title %}
	Home
{% endblock %}

{% block body %}
	<h1 class="text-center mt-4 mb-4" style="color: #2c3e50;"><b>Checking System</b></h1>

<section class="container d-flex flex-row mt-3 w-75">
		
	<div class="d-flex flex-column">

		{% if is_granted('ROLE_ADMIN') %}
		<h1 class="text-center">Last Week Subjects</h1>
		{% else %}
		<h1 class="text-center">My Subjects</h1>
		{% endif %}
<div class="tableau bg-myColor p-4 rounded d-flex justify-content-center flex-column">
    <table class="table border border-secondary ">
        <thead>
            <tr>
                <th>Teacher</th>
				<th>Subject</th>
				<th>Class</th>
                <th>Date</th>
				<th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% if is_granted('ROLE_ADMIN') %}
            {% for allSubject in subjects %}
			{% set lastWeek = 'now -7 days'|date('Y-m-d') %}
			{% if allSubject.startAt|date('Y-m-d') > lastWeek %}
				<tr>
				 
                    <td>{{ allSubject.teacherName }}</td>
                    <td>{{ allSubject.subjectName }}</td>
                    <td>{{ allSubject.scheduleId.classeSchedule }}</td>
                    <td>{{ allSubject.startAt ? allSubject.startAt|date('Y/m/d') : '' }}</td> 
					<td>
						<a class="" href="{{ path('app_subject_show', {'id': allSubject.id}) }}"><img src="{{ asset('assets/local-img/button/eye.png') }}" width="30px" height="30px" class="img-fluid"></a>
					</td>
                </tr>
			{% endif %}
            {% endfor %}
       
            {% else %}
        {% for subject in my_subjects %}
		{% set lastWeek = 'now -7 days'|date('Y-m-d') %}
		{% if subject.startAt|date('Y-m-d') > lastWeek %}
		<tr>
                <td>{{ subject.teacherName }}</td>
                <td>{{ subject.subjectName }}</td>
                <td>{{ subject.scheduleId.classeSchedule }}</td>
                <td>{{ subject.startAt ? subject.startAt|date('Y/m/d') : '' }}</td>
                <td>
					<a class="" href="{{ path('app_subject_show', {'id': subject.id}) }}"><img src="{{ asset('assets/local-img/button/eye.png') }}" width="30px" height="30px" class="img-fluid"> </a>
                </td>
            </tr>
		
			{% endif %}
        {% endfor %}
        {% endif %}
        </tbody>
    </table>
</div>

{# <div class="w-100">
	<div class="card mt-3 bg-myColor">
		<div class="card-header">
			<h3 class="text-center">Box</h3>
		</div>
		<div class="card-body">
			<div class="row">
				<div class="col-6">
					<p class="card-text">Data</p>
				</div>
			</div>
		</div>
	</div>
</div> #}

</div>

<div class="w-100">
	<h1 class="text-center mt-4 mb-4">Shortcuts</h1>
	<div class="d-flex flex-wrap justify-content-center">
		<div class="col-4 m-3">
			<div class="card">
				<a href="{{ path('app_calendar_index') }}" class="btn" style="background-color: #2c3e50; color: #fff;">
					<div class="card-body p-4">
						<h5 class="card-title">Calendar</h5>
						{# <p class="card-text">View all calendar</p> #}
					</div>
				</a>
			</div>
		</div>
		<div class="col-4 m-3">
			<div class="card">
				<a href="{{ path('app_student_all') }}" class="btn" style="background-color: #2c3e50; color: #fff;">
					<div class="card-body p-4">
						<h5 class="card-title">Student List</h5>
						{# <p class="card-text">View all students</p> #}
					</div>
				</a>
			</div>
		</div>
		<div class="col-4 m-3">
			<div class="card">
				<a href="{{ path('app_users') }}" class="btn" style="background-color: #2c3e50; color: #fff;">
					<div class="card-body p-4">
						<h5 class="card-title">Users</h5>
						{# <p class="card-text">View all users</p> #}
					</div>
				</a>
			</div>
		</div>
		<div class="col-4 m-3">
			<div class="card">
				<a href="{{ path('app_student_presence') }}" class="btn" style="background-color: #2c3e50; color: #fff;">
					<div class="card-body p-4">
						<h5 class="card-title">Attendance</h5>
						{# <p class="card-text">View all Presence</p> #}
					</div>
				</a>
			</div>
		</div>
	</div>
</div>
</section>
{% endblock %}